name: Deployment

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install Yarn
      - name: Install Yarn
      run: npm i -g yarn@berry

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the site
      - name: Build page
        run: yarn build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_SSH_PRIVATE }}
          publish_dir: ./build
          publish_branch: master
          exclude_assets: "{./!(analysis)/**,./!(asset-manifest.json)}"
